import json
import uuid
from pathlib import Path

from backend.forge.config import DEFAULT_ATTACK_AMOUNT


def create_cash_out_attack(account):
    """
    Create the final high-value cash-out event.

    The attack happens after the account has already
    built up a normal behavioral history.
    """

    attack = {
        "attack_id": "ATT-" + uuid.uuid4().hex[:8].upper(),
        "account_id": account["account_id"],
        "day": 180,
        "attack_type": "CASH_OUT",
        "amount": DEFAULT_ATTACK_AMOUNT,
        "location": account["city"],
        "device_id": account["primary_device"],
        "is_fraud": True,
    }

    return attack


def save_attack(attack):
    """Save the attack event as JSON."""

    output_folder = Path("data/generated")
    output_folder.mkdir(parents=True, exist_ok=True)

    file_path = output_folder / "attacks.json"

    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(attack, file, indent=4)

    return file_path


if __name__ == "__main__":

    # Load the account generated by Forge.
    account_file = Path("data/generated/accounts.json")

    if not account_file.exists():
        print("accounts.json not found.")
        print("Run generator first:")
        print("python -m backend.forge.generator")
        exit()

    with open(account_file, "r", encoding="utf-8") as file:
        account = json.load(file)

    attack = create_cash_out_attack(account)

    save_attack(attack)

    print("Attack created")
    print("-------------------------")
    print(f"Attack ID : {attack['attack_id']}")
    print(f"Account   : {attack['account_id']}")
    print(f"Type      : {attack['attack_type']}")
    print(f"Amount    : ₹{attack['amount']}")
    print(f"Day       : {attack['day']}")